### PR TITLE
Update people: Add Peilun Zhang

### PR DESCRIPTION
**Pull request by Pezhin**
I feel a little bit awkward of putting the face-pic of mine. Can I use the generic-male pic?

### CODE REVIEW

**Comment by kyleheadley** [comment]
You switched the categories, with yourself as graduate and me as undergrad. Thanks for adding the results, though!

**Comment by Pezhin** [comment]
@kyleheadley Is there anything wrong with the category? I am not very familiar with updating the xml database. But it looks to me that the categories are not wrong?
https://github.com/Pezhin/cuplv.github.io/blob/558efaca5862a9a2217682de8b1e2a50094f8416/pl.xml#L15
https://github.com/Pezhin/cuplv.github.io/blob/558efaca5862a9a2217682de8b1e2a50094f8416/pl.xml#L26

**Comment by kyleheadley** [comment]
Oh, I'm sorry, it looks correct now. I looked at it twice and thought it was switched. I guess I'm still tired from the travel. I'll click Evan's name to request a review for you, in case he hasn't seen this.

**Comment by bechang** [comment]
@Pezhin It would be better if you would be willing to put up your headshot? If you really, really are strongly against it, that's ok.

**Pull request merged**
